### PR TITLE
fix: bypass load permission if migrations not completed

### PR DESCRIPTION
**Pull request by navinkarkera**
## Description

This MR fixes tutor build failure due to permissions file being loaded before migrations. The fix is inspired by https://github.com/eduNEXT/eox-tenant/pull/145

## Testing instructions

Install this plugin in tutor and run `tutor images build openedx`, it will fail with database `ImproperlyConfigured` error. Update your local copy of plugin with this change and run build, it should work.

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [x] Rebased master/main
- [x] Squashed commits

### CODE REVIEW

**Comment by Alec4r** [comment]
@santiagosuarezedunext could you help me with this?

**Comment by Alec4r** [comment]
Hi!! @navinkarkera,

We are planning to add this review in our next sprint, we will make test in a remote environment,

I hope have good news for you soon.

Thanks for the PR.

**Review by MaferMazu — APPROVED** [review]
This looks good to me. And this implements something similar to #145 

What do you think @Alec4r @JuanDavidBuitrago @dcoa @luisfelipec95?

**Review by MaferMazu — APPROVED** [review]
This looks good to me. And this implements something similar to #145 

What do you think @Alec4r @JuanDavidBuitrago @dcoa @luisfelipec95?

**Review by JuanDavidBuitrago — APPROVED** [review]
It looks good! It's similar as you say @MaferMazu

**Comment by JuanDavidBuitrago** [comment]
@Alec4r,  @MaferMazu how we can continue with this? It is blocked for unsigned commits.

**Comment by MaferMazu** [comment]
I didn't notice that we need signed commits 🙈

@navinkarkera, can you [sign this commit](https://docs.github.com/en/authentication/managing-commit-signature-verification) to merge this?

**Comment by navinkarkera** [comment]
> I didn't notice that we need signed commits see_no_evil
> 
> @navinkarkera, can you [sign this commit](https://docs.github.com/en/authentication/managing-commit-signature-verification) to merge this?

@MaferMazu Done.

**Pull request merged**
