### PR TITLE
perf: add Quince support DS-776

### PR DESCRIPTION
**Pull request by MaferMazu**
## Description

This PR brings support to the Open edX Quince release.
- Updated the GitHub actions.
- Update the core and normal requirements.
- Update the readme.
- The test cases work.

## Testing instructions

Follow the test case file: https://docs.google.com/document/d/1921hOajxAYrdin_thEZ005aQBwPNoj2zsbgkf3q1Mjc/edit?usp=sharing

## Additional information

I added some changes to improve the code and follow the pycodestyle and the pylint rules.

## Checklist for Merge

- [x] Updated documentation
- [x] Rebased master/main
- [x] Squashed commits

### CODE REVIEW

**Review by dcoa — APPROVED** [review]
This looks good to me. 

I test the multitenancy funtions and works

**Review by bra-i-am — APPROVED** [review]
Working as expected!

**Review by Asespinel — APPROVED** [review]

**Comment by MaferMazu** [comment]
I forgot to update the readme; I'll update it and merge this. Thanks for the reviews.

**Comment by MaferMazu** [comment]
I also removed the --settings=production from the doc because that was the cause of the errors. The commands will take the settings of the env they are running.

**Comment by Asespinel** [comment]
LGTM!

**Review by Asespinel — APPROVED** [review]

**Review by bra-i-am — APPROVED** [review]
I forgot to review the docs before, sorry about that

Approved!

**Pull request merged**
