### PR TITLE
refactor: use CourseEnrollmentQuerysetRequested from openedx-filters

### PR DESCRIPTION
**Pull request by JuanDavidBuitrago**
## Description

This PR make a refactor to use FFI-3 with [openedx-filters](https://github.com/openedx/openedx-filters/blob/main/openedx_filters/learning/filters.py#L523)
Refactor from https://github.com/eduNEXT/eox-tenant/pull/156

## Testing instructions

1. Create two Tenant sites and add at less one course on each one. Go on to create sites: http://{lms.base}:8000/admin/eox_tenant/tenantconfig/
2. In a course, in Studio, set ``Mobile Course Available`` true. Go on to configure the key: http://{studio.base}:8001/settings/advanced/{your_course_id}
3. Enroll a user (user don't have to be a staff user) in a course on different sites.
4. Add the following configurations to your configuration site.
```json
"OPEN_EDX_FILTERS_CONFIG": {
    "org.openedx.learning.course_enrollment_queryset.requested.v1": {
        "fail_silently": false,
        "pipeline": [
            "eox_tenant.filters.pipeline.FilterUserCourseEnrollmentsByTenant"
        ]
    }
},
```
5. Make a request in:
- my_microsite.{lms.base}:8000/api/enrollment/v1/enrollment
- my_microsite.{lms.base}:8000/api/mobile/v1/users/{username}/course_enrollments/
6. You should see the courses where you are enrolled. Check when you don't use ``OPEN_EDX_FILTERS_CONFIG`` in your site, the request show all courses.

## More information

You can try the steps in https://github.com/eduNEXT/eox-tenant/pull/156 with edx-platform [branch](https://github.com/openedx/edx-platform/pull/31331)

### CODE REVIEW

**Comment by Alec4r** [comment]
Hi @JuanDavidBuitrago , I wanna know if this PR is still important, or maybe we could close it.

**Comment by santiagosuarezedunext** [comment]
I undertand that this PR need review so I am going to create a card for it to check it in the next sprint

**Comment by JuanDavidBuitrago** [comment]
Hi @Alec4r Its important, but first we need upstream PR is merge: https://github.com/openedx/edx-platform/pull/31331

**Comment by JuanDavidBuitrago** [comment]
I'm going to continue working on it, it has to be merged in this sprint

**Review by luisfelipec95 — APPROVED** [review]

**Review by Asespinel — APPROVED** [review]

**Pull request merged**
