### PR TITLE
perf: filter certificates by organization and remove certificate proxy DS-305

### PR DESCRIPTION
**Pull request by MaferMazu**
## Description

This PR corresponds to the feature [JU-3](https://docs.google.com/document/d/1BtEShTyy5I9g_noIX0vA70dp_Oq4dCqKjCUdQN9xM5o/edit?usp=sharing). This adds a filter to render certificates by organizations.

Changes:
- Adds the pipeline step filter and its tests.
- Remove all about to Certificates Proxy.
    - The proxy setup in tenant_wise/__init__ and a method that is only used for that proxy.
    - The CertificateManager, ElegibleCertificateManager, and the GeneratedCertificateProxy.
    - The Certificate Proxy setting in common.
 - Remove all about the certificates backend (settings, tests, and the backend).
 - Fix quality test.

### In stage

- Enter in stage (Ex: https://tenant-a.nutmeg-live.edunext.link/courses)
- Create an account.
- Enroll in Course Tenant A 2 or Course Test Certificate 2.
- If the milestone works well, you are going to need to pass the first version of that course.
- Enroll in the first version of that course and pass it.
- Go to progress and request your certificate.
- You are able to see your certificate, but if you change the tenant you can't see your certificate.
- Then you can start Course Tenant A 2 or Course Test Certificate 2.

The last two steps test whether the feature works correctly.

### In local

Requisites
- A tutor env with this eox-tenant version.
    - You can add this in the config.yml:
```
OPENEDX_EXTRA_PIP_REQUIREMENTS:
- git+https://github.com/eduNEXT/eox-tenant.git@nu/ednx/ju-3#egg=eox-tenant
```
- You need a tenant config with  `"EDNX_USE_SIGNAL": true` and  `"OPEN_EDX_FILTERS_CONFIG"` defined. And have a tenant route with that config. Example of tenant:
```
{
    "EDNX_USE_SIGNAL": true,
    "OPEN_EDX_FILTERS_CONFIG": {
        "org.openedx.learning.certificate.render.started.v1": {
            "fail_silently": false,
            "pipeline": [
                "eox_tenant.filters.pipeline.FilterRenderCertificatesByOrg"
            ]
        }
    },
    "PLATFORM_NAME": "Tenant A",
    "SITE_NAME": "tenant-a.nutmeg.edunext.link",
    "course_org_filter": [
        "tenantA"
    ]
}
```

- You need a course with certificates.
    - Create a course with the tenant course_org_filter in Studio.
    - In LMS Admin, set Honor that course.
    - In Studio > Course > Settings > Schedule, change the start date.
    - In Studio > Course > Settings > Grading, set Homework total grade 100, total number 1, and dropable 0. Delete the rest.
    - In Studio > Content > Outline create a section, subsection, and unit with a problem. Then in the settings of the subsection, and add the previous step grading.
    - In Admin LMS > Certificates > Certificate generation configurations, create a enable element.
    - In Studio > Settings > Advanced click over Show Deprecated Settings and set Certificates Downloadable Before End to true.
    - In Studio > Settings > Certificates, create a certificate and activate it. (If you want to confirm, click Live Preview)
    - With an admin account in LMS > Course > Instructor > Certificate, enable the student to generate the certificate.

- Note: I don't know if it is necessary but I also added a enable element in Admin LMS > Grades > Persistent grades enabled flag.

Step by Step to verify the filter

- Create a user in the tenant.
- Enroll the user in the course.
- Pass the course.
- In Progress generate the certificate.
- View the certificate.
- Try to view that certificate with another tenant. (other-tenant/certificates/id-certificate) - You can't see it.

Step by Step to verify the milestones

- Create another course.
- Make the first one a requirement for the new one (In Studio > Settings > Scheduling > Prerequisite)
- The milestone will be generated on the admin site.
- Complete the prerequisite course, and a user milestone must be generated.

More info: [JU-3](https://docs.google.com/document/d/1BtEShTyy5I9g_noIX0vA70dp_Oq4dCqKjCUdQN9xM5o/edit?usp=sharing)

## Checklist for Merge

- [x] Tested in a remote environment
- [x] Updated documentation
- [x] Rebased master/main
- [x] Squashed commits

### CODE REVIEW

**Comment by MaferMazu** [comment]
Thanks, @dcoa; I already edit the PR instructions.

**Comment by danielsgz** [comment]
Using stack strain with @JuanDavidBuitrago and the following strain.yml file:

```
STRAIN_NAME: nuez
STRAIN_TUTOR_VERSION: v14.1.0
DEV_PROJECT_NAME: nuez_dev
LOCAL_PROJECT_NAME: nuez_local
CMS_HOST: studio.nuez.edunext.link
LMS_HOST: lms.nuez.edunext.link
PLATFORM_NAME: Distro nuez
EDX_PLATFORM_REPOSITORY: https://github.com/eduNEXT/edunext-platform.git
EDX_PLATFORM_VERSION: ednx-release/nuez.master
DOCKER_IMAGE_OPENEDX: docker.io/ednxops/distro-edunext-edxapp:nuez-06122022
DOCKER_IMAGE_OPENEDX_DEV: docker.io/ednxops/distro-edunext-edxapp-dev:nuez-06122022
STRAIN_TUTOR_PLUGINS:
  - REPO: tutor-contrib-edunext-distro
    VERSION: v3.1.0
    EGG: tutor-contrib-edunext-distro==v3.1.0
    PACKAGE_NAME: distro
    PROTOCOL: ssh
  - REPO: tutor-contrib-codejail
    VERSION: v14.0.0
    EGG: tutor-contrib-codejail==v14.0.0
    PACKAGE_NAME: codejail
STRAIN_EXTRA_COMMANDS:
  - APP: 'tutor'
    COMMAND: 'distro enable-themes'
  - APP: 'tutor'
    COMMAND: 'local init --limit=codejail'
  - APP: 'tutor'
    COMMAND: 'dev init --limit=codejail'
  - APP: 'tutor'
    COMMAND: 'distro enable-private-packages'
STRAIN_VOLUME_OVERRIDES:
  edxapp:
    - DESTINATION: ../../src/edxapp/edx-platform
      LOCATION: /openedx/edx-platform
    # Themes
    - DESTINATION: ../../src/themes/ednx-saas-themes
      LOCATION: /openedx/themes/ednx-saas-themes
    # Public eox
    - DESTINATION: ../../src/edxapp/eox-core
      LOCATION: /openedx/extra_deps/eox-core
    - DESTINATION: ../../src/edxapp/eox-tagging
      LOCATION: /openedx/extra_deps/eox-tagging
    - DESTINATION: ../../src/edxapp/eox-tenant
      LOCATION: /openedx/extra_deps/eox-tenant
    - DESTINATION: ../../src/edxapp/eox-hooks
      LOCATION: /openedx/extra_deps/eox-hooks
    - DESTINATION: ../../src/edxapp/eox-audit-model
      LOCATION: /openedx/extra_deps/eox-audit-model
    - DESTINATION: ../../src/edxapp/eox-theming
      LOCATION: /openedx/extra_deps/eox-theming
    # Private eox
    - DESTINATION: ../../src/edxapp/eox-manage
      LOCATION: /openedx/extra_deps/eox-manage
    - DESTINATION: ../../src/edxapp/eox-support
      LOCATION: /openedx/extra_deps/eox-support
STRAIN_EXPORT_VOLUMES:
  - CONTAINER: lms
    LOCATION: /openedx/edx-platform
    DESTINATION: src/edxapp/edx-platform
  # Themes
  - CONTAINER: lms
    LOCATION: /openedx/themes/ednx-saas-themes
    DESTINATION: src/themes/ednx-saas-themes
  # Public eox
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-core
    DESTINATION: src/edxapp/eox-core
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-tagging
    DESTINATION: src/edxapp/eox-tagging
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-tenant
    DESTINATION: src/edxapp/eox-tenant
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-hooks
    DESTINATION: src/edxapp/eox-hooks
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-audit-model
    DESTINATION: src/edxapp/eox-audit-model
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-theming
    DESTINATION: src/edxapp/eox-theming
  # Private eox
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-manage
    DESTINATION: src/edxapp/eox-manage
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-support
    DESTINATION: src/edxapp/eox-support
DISTRO_EOX_MANAGE_DPKG:
  index: git
  name: eox-manage
  repo: eox-manage
  domain: github.com
  path: eduNEXT
  protocol: ssh
  private: true
  variables:
    development: {}
    production: {}
  version: v3.0.0
DISTRO_EOX_SUPPORT_DPKG:
  index: git
  name: eox-support
  private: true
  repo: eox-support
  domain: github.com
  path: eduNEXT
  protocol: ssh
  variables:
    development:
      EOX_SUPPORT_BULK_EMAIL_BACKEND: eox_support.edxapp_wrapper.backends.bulk_email_l_v1
      EOX_SUPPORT_EDXMAKO_BACKEND: eox_support.edxapp_wrapper.backends.edxmako_l_v1
      EOX_SUPPORT_STUDENT_BACKEND: eox_support.edxapp_wrapper.backends.student_l_v1
      EOX_SUPPORT_THIRD_PARTY_AUTH_BACKEND: eox_support.edxapp_wrapper.backends.third_party_auth_l_v1
      EOX_SUPPORT_UTIL_BACKEND: eox_support.edxapp_wrapper.backends.util_l_v1
      EOX_SUPPORT_CERTIFICATES_BACKEND: eox_support.edxapp_wrapper.backends.certificates_m_v1
    production:
      EOX_SUPPORT_BULK_EMAIL_BACKEND: eox_support.edxapp_wrapper.backends.bulk_email_l_v1
      EOX_SUPPORT_EDXMAKO_BACKEND: eox_support.edxapp_wrapper.backends.edxmako_l_v1
      EOX_SUPPORT_STUDENT_BACKEND: eox_support.edxapp_wrapper.backends.student_l_v1
      EOX_SUPPORT_THIRD_PARTY_AUTH_BACKEND: eox_support.edxapp_wrapper.backends.third_party_auth_l_v1
      EOX_SUPPORT_UTIL_BACKEND: eox_support.edxapp_wrapper.backends.util_l_v1
      EOX_SUPPORT_CERTIFICATES_BACKEND: eox_support.edxapp_wrapper.backends.certificates_m_v1
  version: v4.0.0
DISTRO_EOX_THEMING_DPKG:
  index: git
  name: eox-theming
  private: false
  repo: eox-theming
  domain: github.com
  path: eduNEXT
  protocol: https
  variables:
    development:
      GET_BRANDING_API: eox_tenant.edxapp_wrapper.backends.branding_api_l_v1
      EOX_THEMING_CONFIG_SOURCES: [
        "from_eox_tenant_microsite_v2",
        "from_django_settings"
      ]
    production:
      GET_BRANDING_API: eox_tenant.edxapp_wrapper.backends.branding_api_l_v1
      EOX_THEMING_CONFIG_SOURCES: [
        "from_eox_tenant_microsite_v2",
        "from_django_settings"
      ]
  version: v4.0.1
DISTRO_THEMES_NAME:
  - bragi
  - bragi-00695c
  - bragi-29b6f6
  - bragi-66bb6a
  - bragi-ad1457
  - bragi-fb8c00
  - bragi-00838f
  - bragi-2e7d32
  - bragi-673ab7
  - bragi-c0ca33
  - bragi-fdd835
  - bragi-00897b
  - bragi-37474f
  - bragi-6a1b9a
  - bragi-c62828
  - bragi-ff5722
  - bragi-009688
  - bragi-3949ab
  - bragi-6d4c41
  - bragi-cddc39
  - bragi-ff7043
  - bragi-00acc1
  - bragi-3f51b5
  - bragi-78909c
  - bragi-d4e157
  - bragi-ff8f00
  - bragi-00bcd4
  - bragi-42a5f5
  - bragi-795548
  - bragi-d81b60
  - bragi-ff9800
  - bragi-0277bd
  - bragi-43a047
  - bragi-7cb342
  - bragi-d84315
  - bragi-ffa726
  - bragi-039be5
  - bragi-4527a0
  - bragi-7e57c2
  - bragi-e53935
  - bragi-ffb300
  - bragi-03a9f4
  - bragi-4caf50
  - bragi-8bc34a
  - bragi-e91e63
  - bragi-ffc107
  - bragi-1565c0
  - bragi-4e342e
  - bragi-8d6e63
  - bragi-ec407a
  - bragi-ffca28
  - bragi-1e88e5
  - bragi-546e7a
  - bragi-8e24aa
  - bragi-ef5350
  - bragi-ffeb3b
  - bragi-2196f3
  - bragi-558b2f
  - bragi-9c27b0
  - bragi-ef6c00
  - bragi-ffee58
  - bragi-26a69a
  - bragi-5c6bc0
  - bragi-9ccc65
  - bragi-f44336
  - bragi-26c6da
  - bragi-5e35b1
  - bragi-9e9d24
  - bragi-f4511e
  - bragi-283593
  - bragi-607d8b
  - bragi-ab47bc
  - bragi-f9a825
OPENEDX_EXTRA_PIP_REQUIREMENTS:
  - openedx-scorm-xblock==14.0.0
```

we complete all the described requirements in LMS Amin and Studio to create a course in certificates without any issues. However, during the 'Step by Step to verify the filter' section we faced an issue, specifically in 'In Progress generate the certificate', as the mentioned certificate generation was not possible. There was no button or anything related to this matter, making it impossible to generate such certificate. In fact, we went back to the 'note' step at the end of the instructions to check if it was something needed in order to get the mentioned certificate, but it was again unsuccessful. 

We will like to know if, in order to complete the third and last section of the review, the 'Step by Step to verify the filter' is needed or if one could go on without it, for the sake of timing with this PR. Also, we were wondering if this was the same issue that @dcoa faced when doing her review.

**Review by Henrrypg — APPROVED** [review]
For my side it worked as expected.


image

image

**Comment by dcoa** [comment]
I couldn't make this worth it, fist the certificate is not generated automatically, then I add the user to the certificate white list and create the certificate, in my fest time to test I only saw the "Cannot find certificate" message even in the tenant associated to the course.

I try to create a new user and a new course (add to whitelist to generate the certificate), and with this, I saw the certificate in all the tenants.

**Comment by Henrrypg** [comment]
@dcoa Here are my tenant configs:
Site 1
```
{
    "EDNX_USE_SIGNAL": true,
    "OPEN_EDX_FILTERS_CONFIG": {
        "org.openedx.learning.certificate.render.started.v1": {
            "fail_silently": false,
            "pipeline": [
                "eox_tenant.filters.pipeline.FilterRenderCertificatesByOrg"
            ]
        }
    },
    "PLATFORM_NAME": "Site 1",
    "SITE_NAME": "site1.nuez.edunext.link",
    "course_org_filter": [
        "edx"
    ]
}
```

Site 2
```

{
    "EDNX_USE_SIGNAL": true,
    "FEATURES": {
        "CERTIFICATES_INSTRUCTOR_GENERATION": true,
        "CUSTOM_CERTIFICATE_TEMPLATES_ENABLED": true
    },
    "LMS_BASE": "site2.nuez.edunext.link:8000",
    "LMS_ROOT_URL": "http://site2.nuez.edunext.link:8000",
    "OPEN_EDX_FILTERS_CONFIG": {
        "org.openedx.learning.certificate.render.started.v1": {
            "fail_silently": false,
            "pipeline": [
                "eox_tenant.filters.pipeline.FilterRenderCertificatesByOrg"
            ]
        }
    },
    "SITE_NAME": "site2.nuez.edunext.link",
    "course_org_filter": [
        "site2"
    ]
}
```

I realize that all tenant needs to run this pipeline to run properly.

**Review by JuanDavidBuitrago — APPROVED** [review]
Excellent!!! @MaferMazu, I tested and it's working as expected
I tested in stage:

- [x] Milestones
- [x] Get a certificate
- [x] Don't show in different tenant

**Comment by MaferMazu** [comment]
Thanks to all for the effort in testing this. I'm going to squash and merge :D

**Pull request merged**
