### PR TITLE
refactor: inherit from social auth exception

### PR DESCRIPTION
**Pull request by johanseto**
## Description

* refactor: inherit from social auth exception

This change the heritance of the eox-tenant-auth-exception.

This with the purpose of the exception to be handled by the social tpa middleware exception process.

You can see here that the new class is also based in value error exception. https://github.com/python-social-auth/social-core/blob/29cbbd22b98d81d569a886b1cc0bd9a316cd124f/social_core/exceptions.py#L1

But the change is related with this PR:
https://github.com/eduNEXT/eox-core/pull/171
So now as the exception is family  of the SocialAuthBaseException.

The the tpa middleware could managed it.
https://github.com/python-social-auth/social-app-django/blob/5.4.0/social_django/middleware.py#L35

Keep in mind that this middleware is parent of edx-platform middleware. https://github.com/openedx/edx-platform/blob/ebcbe1cd9208191c0589d7fe538c6ac13470abe6/common/djangoapps/third_party_auth/middleware.py#L18

* refactor: social-auth-core pkg inclusion

(cherry picked from commit c542749eceab893ec351cfd7a056f679de760d26)

### Please before review  or approve the [commitlint-PR](https://github.com/eduNEXT/eox-tenant/pull/193) or I can't add links or urls in the commits body.

PR related the change:
https://github.com/eduNEXT/eox-tenant/pull/192

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Comment by johanseto** [comment]
I am only adding social in base.in 
https://github.com/eduNEXT/eox-tenant/blob/9c22abd231823f4ccfe5402b94c0aaa57bc11aae/requirements/base.in#L12
and the running `make upgrade`.

For some unknown reason I had to change the `setup.cfg` to allow load the pytlint rules... that you can research what is happening with the  pylint upgrade...
here are some ruiles removed in the upgrade v3,0,0 version https://github.com/pylint-dev/pylint/pull/4942

**Comment by bra-i-am** [comment]
hi @johanseto, I hope you're well... could you please solve the conflicts to start with this PR's review? 

Thank you :D

**Comment by johanseto** [comment]
@bra-i-am nice, I have to update a rule to the pyint disable due the update of plint and some yield config that is not under the scope of this PR.
image

**Review by MaferMazu — APPROVED** [review]
This looks good to me.

**Review by dcoa — APPROVED** [review]
looks good

**Pull request merged**
