### PR TITLE
perf: sumac release support `AP-1580`

### PR DESCRIPTION
**Pull request by BryanttV**
## Description

This PR adds support for the Open edX Sumac release.

These were the changes made:

- Upgraded requirements based on the `edx-platform` Sumac release. 
- Updated the Integration Tests to use the Sumac release with Tutor.

## Testing instructions

1. Create an environment with Sumac release, you can use [Tutor](https://docs.tutor.overhang.io/index.html) or [TVM](https://github.com/eduNEXT/tvm).
2. Install the Django plugin `eox-tenant` using this PR branch, you can use the steps in [Tutor documentation](https://docs.tutor.overhang.io/configuration.html#installing-extra-xblocks-and-requirements).
3. Run the [test cases](https://docs.google.com/document/d/1qqsc6FJ9JTx8xx43TvJfvVpy97_BakL-0IGta4bbshg). In this file, you can find more information about the plugin configuration.

## Related Issues
- [Jira (AP-1580)](https://edunext.atlassian.net/browse/AP-1580)

### CODE REVIEW

**Review by MaferMazu — APPROVED** [review]
Thanks for this PR, @BryanttV ✨

You updated the dependencies and the documentation; this works in Tutor, and the backends work well.

I tested principally remotely at https://sumac.releases.edunext.link/, and everything worked as expected. We can have different tenants, and we have access to all of the API endpoints.

I left a brief comment in the Test case document for future review, but the rest looks good.

**Comment by MaferMazu** [comment]
Is there a reason why the integration tests are failing or skipping?

**Comment by magajh** [comment]
> Is there a reason why the integration tests are failing or skipping?

@MaferMazu integration tests in nightly are failing for an unknown error, and as a consequence, the workflows for the other Tutor versions are getting cancelled. I'm going to open a PR with a fix to avoid this

**Comment by magajh** [comment]
Although since Tutor 19 hasn't been released yet, seems like we have no way to know that the integration tests are passing for Sumac

**Comment by BryanttV** [comment]
> has this been tested in a remote env?

Yes @magajh , the changes were deployed and tested in our Sumac stage.

**Comment by magajh** [comment]
@BryanttV  I'd say is not necessary, we can close this PR and open a follow-up task to make sure the tests in Sumac are passing once tutor 19 is released

**Comment by magajh** [comment]
@BryanttV can we rebase with this branch https://github.com/eduNEXT/eox-tenant/pull/232 to see if it works?

**Review by magajh — DISMISSED** [review]

**Review by MaferMazu — APPROVED** [review]
Thanks ✨ It work as expected.

**Review by magajh — APPROVED** [review]

**Pull request merged**
